### ISSUE TITLE
[MSVC] DCTL failed to build due to "error C2039: 'bit_set_fast': is not a member of 'xstd'" with msvc on Windows

### ISSUE THREAD

**Issue by Zhaojun-Liu** [rhalbersma/dctl#33]
Hi,
DCTL failed to build with below errors, it looks a regression issue from bit_set commit https://github.com/rhalbersma/bit_set/commit/06cd028ec3c197b27a6d94a121f21ef1b819793a.
```
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(21): error C2039: 'bit_set_fast': is not a member of 'xstd'
C:\gitP\rhalbersma\dctl\..\bit_set\include\xstd/bit_set.hpp(28): note: see declaration of 'xstd'
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(21): note: the template instantiation context (the oldest one first) is
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(18): note: while compiling class template 'dctl::core::basic_mask'
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(21): error C2061: syntax error: identifier 'bit_set_fast'
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(22): error C2653: 'set_type': is not a class or namespace name
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(22): error C3861: 'max_size': identifier not found
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(22): error C2975: 'MaxValue': invalid template argument for 'boost::uint_value_t', expected compile-time constant expression
C:/gitP/Microsoft/vcpkg/installed/x64-windows/include\boost/integer.hpp(216): note: see declaration of 'MaxValue'
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(25): error C3878: syntax error: unexpected token 'table' following 'expression'
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(25): note: error recovery skipped: 'identifier'
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(30): error C2059: syntax error: '('
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(35): error C2988: unrecognizable template declaration/definition
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(35): error C2143: syntax error: missing ',' before '<end Parse>'
C:\gitP\rhalbersma\dctl\include\dctl/core/board/mask.hpp(35): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
......
```
**More info:**
the related repos and commit I used as follows:
dctl commit: de565a1
bit_set commit: https://github.com/rhalbersma/bit_set/commit/c91bdd514e5e1c12fe1f93e161e62b0d20a07d01

**Repro steps:**
Download the attachment divide.txt.
Open VS2022 x64 Native Tools command.
Run command: cl divide.txt /TP /c /EHsc /std:c++latest

**Repro file:**
[divide.txt](https://github.com/user-attachments/files/15864907/divide.txt)

**Comment by rhalbersma** [comment]
@Zhaojun-Liu `bit_set_fast` had been renamed to `bit_set_aligned`. I've also "ported" some other minor issues from `bit_set` and this repo now compiles cleanly under gcc 14 and gcc 15-SVN as well as Clang 19-SVN. Please test for MSVC!

**Comment by Zhaojun-Liu** [comment]
> @Zhaojun-Liu `bit_set_fast` had been renamed to `bit_set_aligned`. I've also "ported" some other minor issues from `bit_set` and this repo now compiles cleanly under gcc 14 and gcc 15-SVN as well as Clang 19-SVN. Please test for MSVC!

Hi, I can't use the latest code of bit_set for DCTL build since the following issue, seem that aux is an invalid path name on Windows.
![image](https://github.com/rhalbersma/dctl/assets/103498042/c262465d-2be6-4e0d-837e-eb4d0c49e439)

**Comment by rhalbersma** [comment]
Incredibly, this had been reported and fixed 2 years ago: https://github.com/rhalbersma/bit_set/issues/11 🥴 Since aux is such a common dirname on Linux, this had slipped back in again.

Will fix this later today, again.

**Comment by rhalbersma** [comment]
I fixed the broken aux/ path on `bit_set` (renamed to opt/) and also removed the `[[assume]]` attributes (to make it work with Clang 18) which also might have tripped up MSVC. Could you please test again?

**Comment by Zhaojun-Liu** [comment]
> I fixed the broken aux/ path on `bit_set` (renamed to opt/) and also removed the `[[assume]]` attributes (to make it work with Clang 18) which also might have tripped up MSVC. Could you please test again?

I used the latest commit of dctl, Xstd and bitset to build dctl, and it still failed, error message as follows, could you please take a look? Thank you.
```
C:\gitP\rhalbersma\dctl\..\bit_set\include\xstd/bit_set.hpp(188): error C2760: syntax error: 'static' was unexpected here; expected '{'
C:\gitP\rhalbersma\dctl\..\bit_set\include\xstd/bit_set.hpp(188): note: the template instantiation context (the oldest one first) is
C:\gitP\rhalbersma\dctl\..\bit_set\include\xstd/bit_set.hpp(51): note: while compiling class template 'xstd::bit_set'
C:\gitP\rhalbersma\dctl\..\bit_set\include\xstd/bit_set.hpp(188): error C3878: syntax error: unexpected token '{' following 'expression'
C:\gitP\rhalbersma\dctl\..\bit_set\include\xstd/bit_set.hpp(188): note: error recovery skipped: '{ return identifier  . . . identifier'
C:\gitP\rhalbersma\dctl\..\bit_set\include\xstd/bit_set.hpp(190): error C3878: syntax error: unexpected token ')' following 'compound_statement'
C:\gitP\rhalbersma\dctl\..\bit_set\include\xstd/bit_set.hpp(190): error C3878: syntax error: unexpected token ')' following 'statement'
......
```
Repro steps:
1. download the repro file stride.txt.
2. Open VS2022 x64 Native Tools command.
3. Run command: cl stride.txt /TP /c /EHsc /std:c++latest

Repro file:
[stride.txt](https://github.com/user-attachments/files/15894725/stride.txt)

**Comment by rhalbersma** [comment]
@Zhaojun-Liu I have re-opened your issue at bit_set again. Let's first make sure you can compile and run all the tests in that repo before continuing here.

**Comment by rhalbersma** [comment]
I will close this now as you reported it builds fine with the latest `bit_set` repo.
